import 'package:flutter/material.dart';

const List<(String, String)> _rules = [
  // Pâtes
  ('spaghetti', '🍝'),
  ('penne', '🍝'),
  ('tagliatelle', '🍝'),
  ('linguine', '🍝'),
  ('fusilli', '🍝'),
  ('farfalle', '🍝'),
  ('rigatoni', '🍝'),
  ('lasagne', '🍝'),
  ('macaroni', '🍝'),
  ('gnocchi', '🍝'),
  ('nouille', '🍜'),
  ('pâte', '🍝'),
  ('pate', '🍝'),

  // Céréales & féculents
  ('riz', '🍚'),
  ('quinoa', '🌾'),
  ('couscous', '🌾'),
  ('semoule', '🌾'),
  ('boulgour', '🌾'),
  ('orge', '🌾'),
  ('lentille', '🫘'),
  ('pois chiche', '🫘'),
  ('haricot rouge', '🫘'),
  ('haricot blanc', '🫘'),
  ('fève', '🫘'),
  ('pomme de terre', '🥔'),
  ('patate douce', '🍠'),
  ('patate', '🥔'),

  // Pain & boulangerie
  ('croissant', '🥐'),
  ('brioche', '🥐'),
  ('baguette', '🥖'),
  ('pain', '🍞'),
  ('farine', '🌾'),

  // Viande
  ('bacon', '🥓'),
  ('lardons', '🥓'),
  ('jambon', '🍖'),
  ('saucisse', '🌭'),
  ('dinde', '🦃'),
  ('canard', '🦆'),
  ('poulet', '🍗'),
  ('poule', '🍗'),
  ('blanc de poulet', '🍗'),
  ('poitrine', '🍗'),
  ('escalope', '🍗'),
  ('steak', '🥩'),
  ('boeuf', '🥩'),
  ('bœuf', '🥩'),
  ('veau', '🥩'),
  ('agneau', '🥩'),
  ('porc', '🥩'),
  ('lapin', '🥩'),
  ('côte', '🥩'),
  ('cote', '🥩'),
  ('filet', '🥩'),
  ('viande', '🥩'),

  // Poisson & fruits de mer
  ('crevette', '🦐'),
  ('moule', '🦪'),
  ('calamar', '🦑'),
  ('pieuvre', '🐙'),
  ('homard', '🦞'),
  ('crabe', '🦀'),
  ('saumon', '🐟'),
  ('thon', '🐟'),
  ('cabillaud', '🐟'),
  ('merlu', '🐟'),
  ('sardine', '🐟'),
  ('anchois', '🐟'),
  ('poisson', '🐟'),

  // Œufs
  ('oeuf', '🥚'),
  ('œuf', '🥚'),

  // Produits laitiers
  ('beurre', '🧈'),
  ('lait', '🥛'),
  ('crème', '🥛'),
  ('creme', '🥛'),
  ('yaourt', '🫙'),
  ('yogourt', '🫙'),

  // Fromages
  ('mozzarella', '🧀'),
  ('parmesan', '🧀'),
  ('gruyère', '🧀'),
  ('gruyere', '🧀'),
  ('cheddar', '🧀'),
  ('camembert', '🧀'),
  ('brie', '🧀'),
  ('feta', '🧀'),
  ('ricotta', '🧀'),
  ('emmental', '🧀'),
  ('comté', '🧀'),
  ('comte', '🧀'),
  ('roquefort', '🧀'),
  ('fromage', '🧀'),

  // Légumes
  ('tomate', '🍅'),
  ('carotte', '🥕'),
  ('maïs', '🌽'),
  ('mais', '🌽'),
  ('aubergine', '🍆'),
  ('poivron', '🫑'),
  ('piment', '🌶️'),
  ('ail', '🧄'),
  ('oignon', '🧅'),
  ('brocoli', '🥦'),
  ('courgette', '🥒'),
  ('concombre', '🥒'),
  ('épinard', '🥬'),
  ('epinard', '🥬'),
  ('salade', '🥬'),
  ('laitue', '🥬'),
  ('chou', '🥬'),
  ('poireau', '🥬'),
  ('céleri', '🥬'),
  ('celeri', '🥬'),
  ('champignon', '🍄'),
  ('artichaut', '🥦'),
  ('asperge', '🥦'),
  ('navet', '🥦'),
  ('betterave', '🥦'),
  ('radis', '🥦'),
  ('haricot vert', '🫘'),
  ('petits pois', '🫘'),
  ('légume', '🥦'),
  ('legume', '🥦'),

  // Fruits
  ('avocat', '🥑'),
  ('kiwi', '🥝'),
  ('mangue', '🥭'),
  ('ananas', '🍍'),
  ('pastèque', '🍉'),
  ('pasteque', '🍉'),
  ('melon', '🍈'),
  ('fraise', '🍓'),
  ('cerise', '🍒'),
  ('raisin', '🍇'),
  ('pêche', '🍑'),
  ('peche', '🍑'),
  ('abricot', '🍑'),
  ('poire', '🍐'),
  ('citron', '🍋'),
  ('orange', '🍊'),
  ('banane', '🍌'),
  ('pomme', '🍎'),
  ('fruit', '🍎'),

  // Snacks & sucré
  ('chocolat', '🍫'),
  ('cookie', '🍪'),
  ('biscuit', '🍪'),
  ('bonbon', '🍬'),
  ('caramel', '🍮'),
  ('tarte', '🥧'),
  ('gâteau', '🎂'),
  ('gateau', '🎂'),
  ('miel', '🍯'),
  ('confiture', '🍯'),
  ('chips', '🍟'),

  // Condiments & épices
  ('ketchup', '🍅'),
  ('sauce tomate', '🍅'),
  ('moutarde', '🧂'),
  ('mayonnaise', '🧂'),
  ('vinaigre', '🧂'),
  ('huile', '🫒'),
  ('persil', '🌿'),
  ('basilic', '🌿'),
  ('thym', '🌿'),
  ('romarin', '🌿'),
  ('coriandre', '🌿'),
  ('menthe', '🌿'),
  ('curry', '🌶️'),
  ('paprika', '🌶️'),
  ('cumin', '🧂'),
  ('sel', '🧂'),
  ('poivre', '🧂'),
  ('sucre', '🧂'),
  ('épice', '🧂'),
  ('epice', '🧂'),
  ('herbe', '🌿'),

  // Boissons
  ('café', '☕'),
  ('cafe', '☕'),
  ('thé', '🍵'),
  ('jus', '🧃'),
  ('limonade', '🥤'),
  ('soda', '🥤'),
  ('eau', '💧'),
  ('boisson', '🥤'),

  // Surgelés / fast food
  ('pizza', '🍕'),
  ('burger', '🍔'),
  ('nugget', '🍗'),
  ('frites', '🍟'),
  ('glace', '🍦'),
  ('surgelé', '❄️'),
  ('surgele', '❄️'),
];

Widget buildIngredientIcon(String ingredientName) {
  final n = ingredientName.toLowerCase();
  for (final (keyword, emoji) in _rules) {
    if (n.contains(keyword)) {
      return Text(emoji, style: const TextStyle(fontSize: 22));
    }
  }
  return const Text('🫙', style: TextStyle(fontSize: 22));
}
